apiVersion: v1
kind: Service
metadata:
  name: karranamodb
spec:
  clusterIP: "None" # Headless service
  selector:
    app: karranamodb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    - protocol: TCP
      port: 15000
      targetPort: 15000
