kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  EphemeralContainers: true
nodes:
  - role: control-plane
    image: kindest/node:v1.24.3
  - role: worker
    image: kindest/node:v1.24.3
